### ISSUE TITLE
Error: Couldn't find preset "es2016"

### ISSUE THREAD

**Issue by kazzkiq** [JamesTheHacker/Neuron#1]
Just cloned Neutron and tried to run `npm start` and got this error:

``` bash
ERROR in ./entry.js
Module build failed: Error: Couldn't find preset "es2016" relative to directory "/Users/kazzkiq/Sites/neuron-test/Neuron"
    at /Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:321:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/kazzkiq/Sites/neuron-test/Neuron/node_modules/babel-loader/index.js:88:12)
```

The app still opens, but without any styles (and probably without scripts too).

<img width="601" alt="captura de tela 2016-08-15 as 00 33 19" src="https://cloud.githubusercontent.com/assets/1953194/17654910/76645296-627e-11e6-90c3-52db5336f61a.png">

**Node version:** 0.5.8
**npm version:** 3.7.3

**Comment by JamesTheHacker** [comment]
Fixed. Was a typo in `webpack.config.babel.js`.

**Comment by JamesTheHacker** [comment]
Fixed. Was a typo in `webpack.config.babel.js`.
